server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          products-service:
            url: http://localhost:8080/products
            errorDecoder: com.bintics.orders.gateway.ProductsErrorDecoder
            retryer: com.bintics.orders.gateway.ProductsRetryer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fo_ecommerce_orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
