server:
  port: 8081

app:
  gateway:
    products: http://localhost:8080/products

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fo_ecommerce_orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
resilience4j:
  circuitbreaker:
    instances:
      ProductsGateway:
        minimumNumberOfCalls: 69
  timelimiter:
    instances:
      ProductsGateway:
        timeoutDuration: 10s



