server:
  port: 8081

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          products-service:
            url: http://localhost:8080/products/retry
            errorDecoder: com.bintics.orders.gateway.ProductsErrorDecoder
            
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fo_ecommerce_orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
