server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/fo_ecommerce_orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          products-service:
            url: http://localhost:8080/products/retry

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        #enableRandomizedWait: true  #Exponential Backoff + Jitter
        exponentialBackoffMultiplier: 2
    instances:
      products-service:
        baseConfig: default


  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        minimumNumberOfCalls: 4 #despues de 4 fallas el circuito se abre
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3 #Llamadas permitidas cuando esta en estado semi-abierto
        waitDurationInOpenState: PT30S #Una vez el circuito esta abierto, espera 30 segundos, pasado ese tiempo pasa al estado semi-abierto
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      products-service:
        baseConfig: default
